### ISSUE TITLE
The code of analyze the activation

### ISSUE THREAD

**Issue by zhhiyuan** [bymavis/CAS_ICLR2021#2]
In your paper, you analysis the magnitudes  and the activation frequency of channel-wise activation(Figure1 and 2). I would be very grateful if you can share this part of the code.

**Comment by bymavis** [comment]
Sorry for the late reply. I was a bit busy in last few months. Sure, I will upload the frequency analyses code as soon as possible.

**Comment by hkunzhe** [comment]
Hi @bymavis, I have met the same problem. What's the relationship between the magnitude of activation and the channel-wise activation? In Figure 1, it seems that activation values have been normalized to [0, 1]. And in Figure 2, It seems that the activation frequency is for the raw activation before GAP instead of the channel-wise activation, since the maximum number of activation is H*W (32*32 for CIFAR-10). Did I understand correctly?

**Comment by bymavis** [comment]
> Hi @bymavis, I have met the same problem. In Figure 1, is the magnitude of activation the same as the channel-wise activation? And in Figure 2, are you using 1000 samples to count the activation frequency? Did I understand correctly?

Yes, exactly. We use the channel-wise activation in Figure 1 and 1,000 samples from test set in Figure 2. The code is uploaded now. You can refer to the details.

**Comment by zhhiyuan** [comment]
Thanks for your sharing!
